### ISSUE TITLE
I get several errors in the example implementation

### ISSUE THREAD

**Issue by helwy** [matthinc/flutter_cupertino_settings#10]
Currently trying to use the example given as a starting point for my settings page, but I get several errors (red underlines) when I use it, I think I'm doing something wrong but I hope you can assist me with this. All of them in CupertinoSettings() function.

1. `Too many positional arguments: 0 expected, but 1 found.` which affects all the arguments, that was easily handled by adding `items:` before the widget argument.
2. `The constructor returns type 'dynamic' that isn't of expected type 'Widget'.` / `Undefined class 'CupertinoSlider'.` on the second line of the widgets arguments.
3. `The constructor returns type 'dynamic' that isn't of expected type 'Widget'.` on the `new CupertinoSwitch(value: true)` code on the third line.
4. All empty arguments `CSHeaders()` have a `1 required argument(s) expected, but 0 found.` message.
5. `The constructor returns type 'dynamic' that isn't of expected type 'Widget'.` / `Undefined class 'CupertinoActivityIndicator'.` on the seventh line of the widgets arguments.

**Comment by zipibz** [comment]
Take a look at PR https://github.com/matthinc/flutter_cupertino_settings/pull/9
Making that change should fix some of those issues.
