### ISSUE TITLE
Flutter_cupertino_settings conflicts with card_settings

### ISSUE THREAD

**Issue by MuZiLee** [matthinc/flutter_cupertino_settings#18]
Because card_settings >=1.4.2 depends on flutter_cupertino_settings ^0.1.0 and dandankj depends on flutter_cupertino_settings ^0.2.0, card_settings >=1.4.2 is forbidden.
So, because dandankj depends on card_settings ^1.4.2, version solving failed.
pub get failed (1)
![image](https://user-images.githubusercontent.com/7467318/68479057-60ae9880-026c-11ea-81d1-6d039d2dfde0.png)

I need the two libraries to work together, but they clash。

**Comment by SimonIT** [comment]
You can lower the version to `flutter_cupertino_settings: ^0.1.0` or ask card_settings to increase their dependency to `flutter_cupertino_settings: ^0.2.0`

**Comment by jibiel** [comment]
https://github.com/codegrue/card_settings/commit/532a4935fc259d29b8d15693622e0d5191ce1369

Resolved.
