### ISSUE TITLE
Add subtitle to CSSelectionItem

### ISSUE THREAD

**Issue by djimonn** [matthinc/flutter_cupertino_settings#27]
The selection items should have a property `subtitle`. See screenshot from original iOS settings for reference:

![image](https://user-images.githubusercontent.com/50664914/102609291-8377d580-412b-11eb-93a1-faec22e773ba.png)

**Comment by matthinc** [comment]
Thanks, this was implemented in https://github.com/matthinc/flutter_cupertino_settings/pull/28 and is available in version 0.5.0.
