### ISSUE TITLE
Support for Null-Safety

### ISSUE THREAD

**Issue by sageata** [matthinc/flutter_cupertino_settings#29]
Support for null-safety, please :D

**Comment by codegrue** [comment]
Please comment on ETA if this is being worked on. Thanks.

**Comment by codegrue** [comment]
Please comment if there are plans to work on this?

**Comment by xmine64** [comment]
This pull request has a commit for adding null safety supprort
https://github.com/matthinc/flutter_cupertino_settings/pull/28

**Comment by emce** [comment]
@matthinc  - could you merge above pull request and release null-safe version?

**Comment by matthinc** [comment]
Hi,

thanks for pushing this issue and sorry for the late response, I was very busy with by bachelors thesis recently.
I merged the PR (which introduces NULL safety) and updated the version to 0.5.0.

**Comment by xmine64** [comment]
@matthinc Thanks. I was using @n8han 's version of cupertino_flutter_settings, I'll switch to your version.
