### ISSUE TITLE
Need new version on pub.dartlang.org

### ISSUE THREAD

**Issue by jonjon1123** [matthinc/flutter_cupertino_settings#5]
Can we get a new version pushed to [pub.dartlang.org](https://pub.dartlang.org/packages/flutter_cupertino_settings#-versions-tab-) now that the [Dart 2.x issue](https://github.com/matthinc/flutter_cupertino_settings/issues/2) is fixed.

**Comment by tegab** [comment]
i agree with you. I can't update.

**Comment by matthinc** [comment]
Sorry, I cannot push before October because I‘m currently on vacation and have no PC with me.

Maybe someone can fork & push?

**Comment by jonjon1123** [comment]
For now, I have just pulled down the repo and put it local in my project. I can wait till you get back from vacation. Hope you are having a nice time!

**Comment by matthinc** [comment]
Done
